<?php

$cars = [
    [
        "id" => "1", 
        "marca" => 'Volkswagen',
        "modello" => 'Golf',
        "colore" => 'Blu',
        "anno" => '2009',
        "chilometri" => '89000',
        "accessori" => 'Comandi al volante, Sensori di parcheggio, Cerchi in lega',
        "allestimento" =>'R-Line',
        "carburante" => 'Benzina',
        "porte" => '5',
        "cambio" => 'Manuale',
        "posti" => '5',
        "condizioni veicolo" => 'Usato',
        "interni" => 'Alcantara',
        "classe emissioni" => '4',
        "prezzo" => '6200.00',
        "foto" => 'http://auto-esperienza.com/wp-content/uploads/2017/09/vw-golf-vi-6-usata-motore-cambio-sospensioni-elettronica-tdi-dsg-tfsi-difetti-cerchi-cerchioni-fari-e1506715650512.jpg',
        "cavalli" => '122',
        "kilowatt" => '90',
        "cilindrata" => '1390',
    ],
    [
        "id" => "2",
        "marca" => 'Fiat',
        "modello" => 'Panda',
        "colore" => 'Bianco',
        "anno" => '2016',
        "chilometri" => '110000',
        "accessori" => 'Ruotino di scorta',
        "allestimento" =>'4x4',
        "carburante" => 'Diesel',
        "porte" => '5',
        "cambio" => 'Manuale',
        "posti" => '4',
        "condizioni veicolo" => 'Usato',
        "interni" => '',
        "classe emissioni" => '4',
        "prezzo" => '5000.00',
        "foto" => '',
        "cavalli" => '80',
        "kilowatt" => '44',
        "cilindrata" => '1000',
    ],
    [
        "id" => "3",
        "marca" => 'Renault',
        "modello" => 'Twingo',
        "colore" => 'Carta da zucchero',
        "anno" => '2021',
        "chilometri" => '0',
        "accessori" => 'Comandi al volante, Sensori di parcheggio',
        "allestimento" =>'',
        "carburante" => 'Energia Elettricoa',
        "porte" => '5',
        "cambio" => 'Automatico',
        "posti" => '4',
        "condizioni veicolo" => 'Nuovo',
        "interni" => 'Pelle',
        "classe emissioni" => '',
        "prezzo" => '20000.00',
        "foto" => 'https://hd2.tudocdn.net/935236?w=660&h=440',
        "cavalli" => '82',
        "kilowatt" => '60',
        "cilindrata" => '',
    ]
]

?>